<a href="https://colab.research.google.com/github/navneet0613/UCS420/blob/main/Cognitive_Lab_Assignment_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Submitted by: Navneet Kaur(102497009)

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:

a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [3]:
import numpy as np
arr = np.array([2,4,6,8,10])
print('Original Array:',arr)
arr_add = arr+2                 # addition of all elements with 2
print('After addition in the elements:',arr_add)
arr_mul = arr*3                # multiplication of all elements with 3
print('After multiplication in the elements:',arr_mul)
arr_div = arr/2                 # division of all elements with 2
print('After division in the elements:',arr_div)

Original Array: [ 2  4  6  8 10]
After addition in the elements: [ 4  6  8 10 12]
After multiplication in the elements: [ 6 12 18 24 30]
After division in the elements: [1. 2. 3. 4. 5.]


Q.2 Questions on Basic NumPy Array:

a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
# a) reverse the numpy array
arr1 = np.array([1,2,3,6,4,5])
arr2 = np.flip(arr1)
print('Reversed Array:',arr2)

Reversed Array: [5 4 6 3 2 1]


In [9]:
# b) finding the most frequent values and their indice(s)
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1,1,1,2,3,4,2,4,3,3])

x_frequent = np.bincount(x).argmax()
y_frequent = np.bincount(y).argmax()
indice_x = np.where(x == x_frequent)[0]
indice_y = np.where(y == y_frequent)[0]
print("The most frequent number in X array:",x_frequent)
print("The indices of the most frequent number in X array:",indice_x)
print("The most frequent number in Y array:",y_frequent)
print("The indices of the most frequent number in Y array:",indice_y)

The most frequent number in X array: 1
The indices of the most frequent number in X array: [0 5 7 8 9]
The most frequent number in Y array: 1
The indices of the most frequent number in Y array: [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:

a) Access 1st row, 2nd column

b) Access 3rd row, 1st column

In [15]:
arr = np.array([[10,20,30],[40, 50, 60],[70, 80, 90]])
print("Element at the 1st row, 2nd column:",arr[0,1])
print("Element at the 3rd row,1st column:",arr[2,0])

Element at the 1st row, 2nd column: 20
Element at the 3rd row,1st column: 70


Q.4 Write program to create an 1-D NumPy array named 'your_name' with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [20]:
nav = np.linspace(10,100,25)

print("The array:",nav)
print("\nDimensions of the array:",nav.ndim)              #dimensions
print("\nShape of the array:",nav.shape)                  #shape
print("\nTotal elements of the array:",nav.size)          #no. of elements
print("\nDatatype pf elements:",nav.dtype)                #datatype
print("\nTotal bytes consumed by the array:",nav.nbytes)

# Transpose of the array
transpose_nav = nav.reshape(5,5)
print("\nTransposed array:",transpose_nav)

# using the T attribute
print("\nTranspose using T:",nav.T)    # Works only for 2-D or higher-dimensional arrays,swapping rows and columns

The array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]

Dimensions of the array: 1

Shape of the array: (25,)

Total elements of the array: 25

Datatype pf elements: float64

Total bytes consumed by the array: 200

Transposed array: [[ 10.    13.75  17.5   21.25  25.  ]
 [ 28.75  32.5   36.25  40.    43.75]
 [ 47.5   51.25  55.    58.75  62.5 ]
 [ 66.25  70.    73.75  77.5   81.25]
 [ 85.    88.75  92.5   96.25 100.  ]]

Transpose using T: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_'your_name'
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_'your_name'. Resize the array to two rows and three
columns and name it as resized_ ucs420_'your_name'.

In [23]:
ucs420_nav = np.array([[10,20,30,40],
                       [50,60,70,80],
                       [90,15,20,35]])
print("The array:",ucs420_nav)

mean_value = np.mean(ucs420_nav)
median_value = np.median(ucs420_nav)
max_value = np.max(ucs420_nav)
min_value = np.min(ucs420_nav)
unique_elements = np.unique(ucs420_nav)

print("Mean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique Elements:", unique_elements)

reshaped_ucs420_nav = ucs420_nav.reshape(4, 3)
print("\nReshaped_ucs420_nav:\n", reshaped_ucs420_nav)

resized_ucs420_nav = np.resize(ucs420_nav, (2, 3))
print("\nResized_ucs420_nav:\n", resized_ucs420_nav)

The array: [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped (4x3) Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized (2x3) Array:
 [[10 20 30]
 [40 50 60]]
